workflows:
  my-workflow:                   # workflow ID
    name: My workflow name       # workflow name displayed in Codemagic UI
    instance_type: mac_mini_m1   # machine instance type
    max_build_duration: 60       # build duration in minutes (min 1, max 120)
    environment:
      flutter: stable   # Define the channel name, version (e.g. v1.13.4), or fvm for Flutter Version Management
      # xcode: latest     # Define latest, edge or version (e.g. 11.2)
      # cocoapods: 1.9.1  # Define default or version
      # node: 12.14.0     # Define default, latest, current, lts, carbon (or another stream), nightly or version
      # npm: 6.13.7       # Define default, latest, next, lts or version
      # ndk: r21d         # Define default or revision (e.g. r19c)
      # java: 1.8         # Define default, or platform version (e.g. 11)
      # ruby: 2.7.2       # Define default or version
    # cache:
    # triggering:
    # scripts:
    # artifacts: 
    # publishing: 
    
    # groups:             # Define your environment variables groups here
    # - keystore_credentials
    # - app_store_credentials
    # - manual_cert_credentials
    # - firebase_credentials
    # - other
    
    # Android code signing - Add the keystore_credentials group environment variables in Codemagic UI
    # (either in Application/Team variables)
    #     CM_KEYSTORE
    #     CM_KEYSTORE_PASSWORD
    #     CM_KEY_PASSWORD
    #     CM_KEY_ALIAS

    # iOS automatic code signing - Add the app_store_credentials group environment variables
    # in Codemagic UI (either in Application/Team variables)
    #     APP_STORE_CONNECT_ISSUER_ID
    #     APP_STORE_CONNECT_KEY_IDENTIFIER
    #     APP_STORE_CONNECT_PRIVATE_KEY
    #     CERTIFICATE_PRIVATE_KEY

    # iOS manual code signing - Add the manual_cert_credentials group environment variables
    # in Codemagic UI (either in Application/Team variables)
    #     CM_CERTIFICATE
    #     CM_CERTIFICATE_PASSWORD
    #     CM_PROVISIONING_PROFILE

    # Firebase secrets - Add the firebase_credentials group environment variables in Codemagic UI
    # (either in Application/Team variables
    #     ANDROID_FIREBASE_SECRET
    #     IOS_FIREBASE_SECRET
    
    # Add the other group environment variables in Codemagic UI 
    # (either in Application/Team variables
    #     SSH_KEY_GITHUB     # defining an ssh key used to download private dependencies
    #     CREDENTIALS        # publishing a package to pub.dev
    #     APP_CENTER_TOKEN   # publishing an application to App Center